debian: rename certcentral to acme-chief
Bug: T207389
Change-Id: Iabe405f4d03ef21d9a522cd9c5ef3497d2062654

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,33 +4,33 @@ set -e
 
 case "$1" in
   configure)
-    # Add certcentral user
-    if ! getent passwd certcentral > /dev/null; then
+    # Add acme-chief user
+    if ! getent passwd acme-chief > /dev/null; then
         adduser --quiet --system --no-create-home --home /nonexistent \
-            --group --gecos "Central certificates service" certcentral || true
+            --group --gecos "acme-chief service" acme-chief || true
     fi
 
-    chmod 750 /etc/certcentral /var/lib/certcentral \
-              /var/lib/certcentral/live_certs \
-              /var/lib/certcentral/http_challenges \
-              /var/lib/certcentral/dns_challenges
-    chmod 700 /var/lib/certcentral/new_certs /var/lib/certcentral/csrs
+    chmod 750 /etc/acme-chief /var/lib/acme-chief \
+              /var/lib/acme-chief/live_certs \
+              /var/lib/acme-chief/http_challenges \
+              /var/lib/acme-chief/dns_challenges
+    chmod 700 /var/lib/acme-chief/new_certs /var/lib/acme-chief/csrs
 
-    if ! getent group certcentral > /dev/null; then
-        echo "Error: certcentral group does not exist" >&2
+    if ! getent group acme-chief > /dev/null; then
+        echo "Error: acme-chief group does not exist" >&2
         exit 1
     fi
-    chown certcentral:certcentral /etc/certcentral /etc/certcentral/accounts /var/lib/certcentral \
-                                  /var/lib/certcentral/new_certs /var/lib/certcentral/live_certs \
-                                  /var/lib/certcentral/http_challenges /var/lib/certcentral/dns_challenges \
-                                  /var/lib/certcentral/csrs
+    chown acme-chief:acme-chief /etc/acme-chief /etc/acme-chief/accounts /var/lib/acme-chief \
+                                  /var/lib/acme-chief/new_certs /var/lib/acme-chief/live_certs \
+                                  /var/lib/acme-chief/http_challenges /var/lib/acme-chief/dns_challenges \
+                                  /var/lib/acme-chief/csrs
 
     if ! getent passwd www-data > /dev/null; then
         echo "Error: www-data user does not exist" >&2
         exit 1
     fi
 
-    adduser www-data certcentral
+    adduser www-data acme-chief
   ;;
 
   abort-upgrade|abort-remove|abort-deconfigure)
